theme = "catppuccin_mocha"

[editor]
line-number = "relative"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.indent-guides]
render = true
character = "╎"

[editor.lsp]
display-messages = true
display-signature-help-docs = false

[editor.whitespace.render]
newline = "all"

[editor.whitespace.characters]
newline = "⏎"

